defaults:
  - accelerator: cpu
  - model: mlp
  - dataset: mnist
  - optimizer: adam
  - override hydra/launcher: basic
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

seed: 42
device: auto # Auto-discover accelerator e.g. cuda

train:
  epochs: 2
  batch_size: 16
  num_workers: 0
  refresh_rate: 100

hydra:
  # Logging configuration: https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
  verbose: False
  # Logs to stdout and to a file.
  job_logging:
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
      file:
        filename:
          ${hydra.runtime.output_dir}/${hydra.job.name}_${oc.select:hydra.job.num, 0}.log
  # Set the output directory to /tmp to dump logs.
  run:
    dir: /tmp/hydra/logs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir:  /tmp/hydra/logs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}